enum CompanionEvent {
  welcome,
  idle,
  move,
  great,
  blocked,
  hint,
  close,
  win,
  loss,
  boss,
  goodbye,
  challenge,
  lastHeart,
  halfway,
  streak,
}

// Individually written voices: warm, composed, energetic and understated.
const companionDialogue = <Map<CompanionEvent, List<String>>>[
  {
    CompanionEvent.welcome: [
      'Let’s find a way out.',
      'A new little puzzle! Let’s begin.',
      'Ready? One arrow at a time.',
    ],
    CompanionEvent.idle: [
      'Hmm… I’m tracing that bend too.',
      'Take your time. I’m right here.',
      'I wonder which path opens next.',
      'No rush. A little thinking helps.',
      'That tangle has me curious.',
      'I’m following that path with my eyes.',
      'Sometimes a step back makes it clearer.',
      'Let’s trace the whole lane, nice and slowly.',
      'I’ll keep you company while you think.',
    ],
    CompanionEvent.move: [
      'Nice move!',
      'Well spotted!',
      'That one slipped right out!',
      'You found an opening!',
      'A little more breathing room.',
      'Nicely untangled!',
      'There it goes, tail and all!',
      'A clear lane and a happy little escape.',
      'You read that bend just right.',
      'That gives us a little more space.',
    ],
    CompanionEvent.great: [
      'Great move! More exits are open.',
      'You freed a whole bunch of paths!',
      'That was such a good opening!',
      'Now we have room to move!',
      'One little escape made a big difference!',
      'That opened up so many possibilities.',
    ],
    CompanionEvent.blocked: [
      'That lane’s blocked. Try another path.',
      'Oops, something’s still in the way.',
      'Let’s find what’s blocking it.',
      'No worries. Try a different exit.',
    ],
    CompanionEvent.hint: [
      'Follow the blue arrow’s exit lane.',
      'The blue one has room to leave.',
      'Here’s a little clue in blue.',
      'Try the highlighted path.',
    ],
    CompanionEvent.close: [
      'Just a few arrows left!',
      'We’re nearly through this tangle!',
      'So close! Take your time.',
      'Only the last little twists now.',
    ],
    CompanionEvent.win: [
      'Beautifully done!',
      'Every arrow found its way!',
      'You untangled all of it!',
      'That deserves a little cheer!',
      'What a lovely way to untangle the day!',
      'A clear board and a well-earned smile.',
    ],
    CompanionEvent.loss: [
      'A fresh start? Take your time.',
      'We can give it another look.',
      'A little reset might help.',
      'You’ve got another try whenever you’re ready.',
    ],
    CompanionEvent.boss: [
      'You did it! The crown is clear.',
      'The Crown Keeper is defeated!',
      'What a wonderful finish!',
    ],
    CompanionEvent.goodbye: [
      'See you next time!',
      'Enjoy your break!',
      'We’ll pick this up later.',
      'Until the next puzzle!',
    ],
    CompanionEvent.challenge: [
      'A tighter challenge. We can take it slowly.',
      'Fewer hearts, same team. Let’s trace carefully.',
      'Let’s look all the way along each exit.',
      'A little patience will go a long way here.',
    ],
    CompanionEvent.lastHeart: [
      'One heart left. Let’s pause and trace.',
      'We still have a chance. No need to rush.',
      'One heart to protect. Check the full lane.',
      'Let’s make the next tap a thoughtful one.',
    ],
    CompanionEvent.halfway: [
      'Half the arrows are home already!',
      'Look at all that space we’ve made!',
      'We’re past the middle of this tangle.',
      'Halfway through! One path at a time.',
    ],
    CompanionEvent.streak: [
      'Five clean escapes in a row!',
      'You’re finding such a lovely rhythm.',
      'That careful streak is looking good!',
      'Another five safe moves. Nicely done!',
    ],
  },
  {
    CompanionEvent.welcome: [
      'Shall we untangle this one?',
      'A fresh puzzle. Let’s take a look.',
      'One considered move at a time.',
    ],
    CompanionEvent.idle: [
      'Hmm… the exit matters more than the bends.',
      'No hurry. I’m considering the paths too.',
      'A moment of thought is well spent.',
      'There may be a quieter route through.',
      'Let’s give that arrangement another glance.',
      'I’m considering how those paths connect.',
      'The longer lane is worth another look.',
      'A pause can bring the pattern into focus.',
      'There is elegance in taking your time.',
    ],
    CompanionEvent.move: [
      'Nicely judged.',
      'An elegant choice.',
      'Precisely the opening we needed.',
      'A graceful little escape.',
      'Well observed.',
      'That clears some space.',
      'That path is neatly resolved.',
      'A small choice, precisely made.',
      'The way ahead was well read.',
      'Another graceful departure.',
    ],
    CompanionEvent.great: [
      'Beautifully planned. Several paths are free.',
      'One choice, several openings. Excellent.',
      'That untangles quite a few possibilities.',
      'A particularly fine move.',
      'A thoughtful choice with several benefits.',
      'An opening that makes the whole board breathe.',
    ],
    CompanionEvent.blocked: [
      'There is still an obstruction ahead.',
      'Perhaps clear its neighbour first.',
      'Follow the lane a little further.',
      'Another path may make room for this one.',
    ],
    CompanionEvent.hint: [
      'The highlighted path has a clear exit.',
      'Consider the blue arrow’s direction.',
      'A small clue, marked in blue.',
      'This route is ready to leave.',
    ],
    CompanionEvent.close: [
      'Only a few paths remain.',
      'A careful finish is all we need.',
      'The arrangement is almost clear.',
      'Just the final details now.',
    ],
    CompanionEvent.win: [
      'A lovely finish.',
      'Every path, neatly resolved.',
      'Beautifully composed and completed.',
      'Very well played.',
      'An intricate arrangement, neatly settled.',
      'That was a most satisfying resolution.',
    ],
    CompanionEvent.loss: [
      'Shall we look again with fresh eyes?',
      'There is no need to hurry the next attempt.',
      'A new approach may be all it needs.',
      'Let’s begin again when you wish.',
    ],
    CompanionEvent.boss: [
      'The crown is yours. Exquisitely done.',
      'A fitting end to a fine journey.',
      'The Crown Keeper has met its match.',
    ],
    CompanionEvent.goodbye: [
      'Until next time.',
      'Enjoy a quiet moment.',
      'We can return to this later.',
      'A pleasant break to you.',
    ],
    CompanionEvent.challenge: [
      'Fewer hearts call for a considered approach.',
      'Let us give every exit a careful glance.',
      'A finer challenge. Patience suits it well.',
      'Read the entire lane before committing.',
    ],
    CompanionEvent.lastHeart: [
      'One heart remains. A measured pace now.',
      'A moment to examine the next exit.',
      'Our final heart deserves a little care.',
      'No haste. There is still a route forward.',
    ],
    CompanionEvent.halfway: [
      'Half the arrangement has been resolved.',
      'The board is opening up beautifully.',
      'We have reached the quieter half.',
      'A pleasing amount of progress already.',
    ],
    CompanionEvent.streak: [
      'Five consecutive escapes. Well judged.',
      'Your rhythm is remarkably composed.',
      'A fine sequence of considered choices.',
      'Another five clean moves. Very good.',
    ],
  },
  {
    CompanionEvent.welcome: [
      'New maze! Let’s untwist it!',
      'All right, puzzle time!',
      'Let’s see where these arrows want to go!',
    ],
    CompanionEvent.idle: [
      'Hmm… that bend is a sneaky one.',
      'My imaginary gears are turning too.',
      'I’m following the squiggles with you.',
      'Thinking break. No rush!',
      'Which one’s hiding a clear exit?',
      'I’m mentally following that squiggly tail.',
      'That twist looks like a tiny roller coaster.',
      'Thinking hats on. Mine has cat ears.',
      'I’m checking the runway with you.',
    ],
    CompanionEvent.move: [
      'Whoosh! Nice one!',
      'Bye-bye, arrow!',
      'That’s the spot!',
      'Smooth escape!',
      'One twist down!',
      'You caught that opening!',
      'Off it wiggles!',
      'One more squiggle set free!',
      'A perfect little getaway!',
      'That tail took the scenic route!',
    ],
    CompanionEvent.great: [
      'Whoa! That freed a whole bunch!',
      'Big move! Look at those openings!',
      'One arrow, lots of possibilities!',
      'Now that’s an untangling trick!',
      'Big brain, tiny arrow, lots of openings!',
      'You found the traffic jam’s off switch!',
    ],
    CompanionEvent.blocked: [
      'Oops! Traffic ahead.',
      'That one’s stuck behind a neighbour.',
      'Not yet—let’s make some room.',
      'Sneaky blocker! Check the lane.',
    ],
    CompanionEvent.hint: [
      'Psst… follow the blue one!',
      'Blue arrow, clear runway!',
      'A tiny nudge in blue.',
      'This highlighted one can scoot out.',
    ],
    CompanionEvent.close: [
      'Final few! You’ve got this!',
      'The tangle’s almost toast!',
      'Just a tiny knot left!',
      'Nearly a clean board!',
    ],
    CompanionEvent.win: [
      'Woo! All untangled!',
      'That was a lovely little whoosh-fest!',
      'Clear board! Nicely played!',
      'Every arrow escaped. High five!',
      'The last squiggle has officially left!',
      'Operation Untwist: complete!',
    ],
    CompanionEvent.loss: [
      'Rematch with the tangle?',
      'Let’s try a fresh route!',
      'Those bends were sneaky. Another go?',
      'Reset, breathe, untwist!',
    ],
    CompanionEvent.boss: [
      'Crown Keeper? Crown cleared!',
      'Whoa. You untangled the whole crown!',
      'Boss down! What a finish!',
    ],
    CompanionEvent.goodbye: [
      'Catch you later!',
      'Break time. Enjoy!',
      'We’ll untwist more next time!',
      'See you for the next whoosh!',
    ],
    CompanionEvent.challenge: [
      'Fewer hearts! Detective mode, on.',
      'Tricky board. Let’s inspect before we tap!',
      'Tiny heart budget, big thinking time.',
      'Let’s outsmart these twists, one at a time!',
    ],
    CompanionEvent.lastHeart: [
      'One heart! Time for our careful faces.',
      'Last heart. Let’s check that runway twice!',
      'Still in it! Slow and sneaky wins this one.',
      'One little heart to guard. No rush!',
    ],
    CompanionEvent.halfway: [
      'Half the tangle has left the chat!',
      'Halfway! Look at all that elbow room!',
      'We’ve untwisted a big chunk of this thing!',
      'Half gone, half adventure still to go!',
    ],
    CompanionEvent.streak: [
      'Five whooshes, zero bumps!',
      'You’re on a clean-escape roll!',
      'Five more safe escapes. High five!',
      'That’s a seriously smooth little streak!',
    ],
  },
  {
    CompanionEvent.welcome: [
      'New board. Let’s read it.',
      'Let’s find the first opening.',
      'Ready. Follow the exits.',
    ],
    CompanionEvent.idle: [
      'Hmm. Checking the lanes.',
      'Take a moment. The board can wait.',
      'One of these paths has room.',
      'I’m tracing the long route.',
      'No rush. Read the head, then the lane.',
      'Following the line past the gap.',
      'A long tail doesn’t mean a blocked exit.',
      'Checking the distant obstruction.',
      'Quiet board. Plenty to read.',
    ],
    CompanionEvent.move: [
      'Clean move.',
      'Good read.',
      'That works.',
      'Sharp eye.',
      'One less obstacle.',
      'Nicely cleared.',
      'Exit confirmed.',
      'Clear lane. Clean escape.',
      'Another route handled.',
      'Read it. Cleared it.',
    ],
    CompanionEvent.great: [
      'Strong move. Several exits freed.',
      'That unlocked the tangle.',
      'Efficient. More room now.',
      'Good choice. Multiple paths opened.',
      'One removal. Several options.',
      'You found the useful opening.',
    ],
    CompanionEvent.blocked: [
      'Blocked. Trace farther ahead.',
      'Clear the obstruction first.',
      'Not this lane yet.',
      'Another exit comes first.',
    ],
    CompanionEvent.hint: [
      'Blue path. Clear exit.',
      'Follow the highlighted head.',
      'That blue arrow can leave.',
      'A clear route is marked.',
    ],
    CompanionEvent.close: [
      'Last few. Stay steady.',
      'Almost clear.',
      'Just the final paths.',
      'A careful finish.',
    ],
    CompanionEvent.win: [
      'Clean finish.',
      'Board cleared. Well played.',
      'Every path resolved.',
      'Solid work.',
      'Tangle solved. Nicely handled.',
      'Nothing left but a clear board.',
    ],
    CompanionEvent.loss: [
      'Reset. Try another approach.',
      'A fresh look can help.',
      'We can read it again.',
      'No hurry. Another attempt is there.',
    ],
    CompanionEvent.boss: [
      'Crown cleared. Impressive.',
      'The keeper is beaten.',
      'A strong finish to the journey.',
    ],
    CompanionEvent.goodbye: [
      'See you around.',
      'Take your break.',
      'We can finish later.',
      'Until next time.',
    ],
    CompanionEvent.challenge: [
      'Fewer hearts. Read before you tap.',
      'Tighter margin. Same rules.',
      'Trace the whole exit. Then commit.',
      'Careful choices from here.',
    ],
    CompanionEvent.lastHeart: [
      'One heart. Check the lane twice.',
      'Last heart. Stay deliberate.',
      'Still playable. Slow down.',
      'Protect the last heart. Read ahead.',
    ],
    CompanionEvent.halfway: [
      'Half cleared. Keep your focus.',
      'Past the middle. Good progress.',
      'The tangle is thinning.',
      'Half the routes resolved.',
    ],
    CompanionEvent.streak: [
      'Five clean moves. Sharp.',
      'A steady streak. Keep reading.',
      'Another five without a block.',
      'Good rhythm. No wasted taps.',
    ],
  },
];

// One source of truth for the default voice and its shuffle tests.
final companionComments = companionDialogue.first;
